### PR TITLE
feat(plunk\functional):for my best practice

### PR DESCRIPTION
**Pull request by ashwinipujari**
**what** for practice
**reviewers**
- [ ] @anvesh8696

### CODE REVIEW

**Comment by anvesh8696** [comment]
can you attach a screenshot in the comment

**Comment by ashwinipujari** [comment]
**what** with screenshot
- [ ] @anvesh8696 
(https://cloud.githubusercontent.com/assets/23546712/20642775/ed6056d4-b3cc-11e6-9796-afe5669e9a13.PNG)

**Comment by ashwinipujari** [comment]
**what** for practice
capture

**Comment by ashwinipujari** [comment]
**what** changed files
shot

**Pull request merged**
